name = "Smp 4"
author = "jacg311"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb58f515128b14fc0f9f9b7fdf152e45d2461353b92a9108879defc52d25eccd"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
