name = "Smp 4"
author = "jacg311"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bbcc8236e6e89f4d0aefcf4c4239e40c897a065388c6f38dcdd3fd32e5659b6"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
