name = "Smp 4"
author = "jacg311"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2096d170b20c4e79c57478defef129b88f7ee4921bf88add85c27377db221106"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
