name = "Smp 4"
author = "jacg311"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96f152ef41d2809215dc9a33aef742339b941cb9d4539d3536dada5b8b47c40d"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
