name = "Smp 4"
author = "jacg311"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90532e5471a52ff7d490dcd71dfba2f5208082cc4527b2dd17055e7d517c4d33"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
