name = "Smp 4"
author = "jacg311"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ad6046c6698cbc199a91d03e0ebea07fa7d92dff7a09af0730a1c28bac84b68"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
