name = "Smp 4"
author = "jacg311"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4959da1c711cc4da3a6bdc0c7d77413a9d43395b0d3754756cd4504e8d6d60b"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
