name = "Smp 4"
author = "jacg311"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b2d264ba5cdce5e3017605297cf9a6f8cf5d16586b76adac4d533b9415e7988"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
