name = "Smp 4"
author = "jacg311"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6285f06360790b76daf1294b441c4fa34dcfbebcf851f8b2dd695f555f76fe18"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
